// VetConnect build script — runs on Vercel during deploy
// Generates config.js from environment variables

const fs = require('fs');

const url = process.env.SUPABASE_URL;
const anonKey = process.env.SUPABASE_ANON_KEY;
const adminEmail = process.env.SUPER_ADMIN_EMAIL || 'lmarotomar@biovetai.org';

if (!url || !anonKey) {
    console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in Vercel environment variables.');
    process.exit(1);
}

const config = `// Auto-generated by build.js — do not edit manually
window.VETCONNECT_CONFIG = {
    supabase: {
        url: '${url}',
        anonKey: '${anonKey}'
    },
    app: {
        superAdminEmail: '${adminEmail}',
        appName: 'VetConnect'
    }
};
`;

fs.writeFileSync('config.js', config);
console.log('config.js generated successfully.');
